### PR TITLE
Fix new runner errors.

### PR DESCRIPTION
**Pull request by guygastineau**
Following is just my commit message pasted here for convenience.

---

Fix crashes when reading non-fatal GC error from stderr.

The legacy use of `process` in `process->scheme` lead to the test
runner returning false positive syntax error messages to users.  This
path fixes that by handling non-lists in the result of running these
commands and by using the more general `open-process-ports` which
returns `stderr` for the subprocess instead of pointing it at
`stdout`.  This should fix the current issues with the test runner.
Since the guile GC error doesn't stop guile from getting the right
results hopefully it is correctly printed to `stderr`, and guile only
solutions will work.  If somehow that message is sent to `stdout`,
then solutions meant for guile will probably get the results from
running with `chez` scheme.  I hope this is not the case, but it is a
possibilituy that I cannot test since I can't reproduce the guile
error locally :/  This patch uses a smarter method of printing to
`stderr`.  When there are contents in `stderr` during the body of
`process->scheme` they are sent the `current-error-port` by the test
runner.  This let's us inspect the GC error behavior from guile even
when the results get used anyway.

### CODE REVIEW

**Comment by guygastineau** [comment]
Here are some highlights of what this does to mitigate the issues.

1. Use `open-process-ports` instead of `process` to run the test siub-processes with a distinct `stderr`, that is, `stderr` is not simply redirected to `stdout`.  This Fixes the issue of reading something other than the results when an uncommented error or warning is emitted.
2. Check if neither result is a list.  In case this holds report a syntax error to the student.  This is really the only case in which we want them to such an error.
3. Convert non-list results to an empty list before further processing to avoid runtime type errors.  This is after `2`.

That is basically it.  This should fix everything (again).    In the end, the new breakage was my fault for using `assoc` on unverified values.   This PR should unf**k the test runner, and we can finally get these issues closed.

**Comment by guygastineau** [comment]
Uh oh, I forgot to get the new rebase off of main after my last PR.  I'll resolve the conflict locally, and force push.

**Review by ErikSchierboom — APPROVED** [review]
Approving. We'll only really know if it fixes the issue by merging 🤷

**Comment by guygastineau** [comment]
Yeah, that is frustrating.  I will make new issue to explore reproducing the GC warning/error in docker.  In the end I might have to go to the Guile mailing list to get help, although I don't know how much enthusiasm there will be for troubleshooting a bug for guile 2.2 when they have mostly moved on to guile 3.  Of course, there is also the possibility of moving our guile test infra to 3.0, but some students will be using 2.2 in their local environments.  Anyway, that info belongs moreso in the new issue.  Thank you Erik.

**Comment by ErikSchierboom** [comment]
Sure. Sorry that it was a slightly painful process.

**Comment by guygastineau** [comment]
> Sure. Sorry that it was a slightly painful process.

Lol, no problem.  In the end it just made me write a better program than our tests ensure.  I gotta figure out how to make these tests more complete though to guard against regressions.

**Pull request merged**
